# Generated by Django 3.2.5 on 2022-09-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traindata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorize',
            name='method_call',
        ),
        migrations.RemoveField(
            model_name='authorize',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='authorize',
            name='method_parameter',
        ),
        migrations.RemoveField(
            model_name='authorize',
            name='method_return',
        ),
        migrations.RemoveField(
            model_name='cache',
            name='method_call',
        ),
        migrations.RemoveField(
            model_name='cache',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='cache',
            name='method_parameter',
        ),
        migrations.RemoveField(
            model_name='cache',
            name='method_return',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='method_call',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='method_parameter',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='method_return',
        ),
        migrations.RemoveField(
            model_name='fifo',
            name='method_call',
        ),
        migrations.RemoveField(
            model_name='fifo',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='fifo',
            name='method_parameter',
        ),
        migrations.RemoveField(
            model_name='fifo',
            name='method_return',
        ),
        migrations.RemoveField(
            model_name='heartbeat',
            name='method_call',
        ),
        migrations.RemoveField(
            model_name='heartbeat',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='heartbeat',
            name='method_parameter',
        ),
        migrations.RemoveField(
            model_name='heartbeat',
            name='method_return',
        ),
        migrations.RemoveField(
            model_name='pingecho',
            name='method_call',
        ),
        migrations.RemoveField(
            model_name='pingecho',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='pingecho',
            name='method_parameter',
        ),
        migrations.RemoveField(
            model_name='pingecho',
            name='method_return',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='method_call',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='method_parameter',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='method_return',
        ),
        migrations.RemoveField(
            model_name='redundancy',
            name='method_call',
        ),
        migrations.RemoveField(
            model_name='redundancy',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='redundancy',
            name='method_parameter',
        ),
        migrations.RemoveField(
            model_name='redundancy',
            name='method_return',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='method_call',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='method_name',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='method_parameter',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='method_return',
        ),
        migrations.AddField(
            model_name='authorize',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='cache',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='fifo',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='pingecho',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='priority',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='redundancy',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='voting',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
